# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: Messenger AnalytiX
description: "G4 | Hackathon Project"
keywords: "Facebook, takout, data visualization, messenger traffic visualization, hackathon, private data"

# Site settings
url: https://peter-gy.github.io
baseurl: "/fb-messenger-analysis/g4-hack-site"

# Author settings
author:
  name      : Péter Ferenc Gyarmati
  job       : Computer Science Student
  bio       : "A young one trying to improve himself by getting his dirty with as many projects as possible"
  email     : dev.petergy@gmail.com
  github    : https://github.com/peter-gy/

# google_analytics: UA-52446115-1
repo: https://github.com/peter-gy/fb-messenger-analysis